### ISSUE TITLE
Not compatible with Django 4.2

### ISSUE THREAD

**Issue by rdawad** [mazelife/django-redactoreditor#9]
Does not work well with django 4.2.6 while working with forms gives an error 

File "C:\Users\ei12650\PycharmProjects\virtualenvs\kintranet2\lib\site-packages\redactor\widgets.py", line 18, in <module>
    from .utils import LazyEncoder
  File "C:\Users\ei12650\PycharmProjects\virtualenvs\kintranet2\lib\site-packages\redactor\utils.py", line 10, in <module>
    from django.utils.encoding import force_text as force_unicode
ImportError: cannot import name 'force_text' from 'django.utils.encoding'
